package com.webdavmusic.data

import androidx.room.*
import com.webdavmusic.data.model.*
import kotlinx.coroutines.flow.Flow

class Converters {
    @TypeConverter fun fromAudioFormat(f: AudioFormat): String = f.name
    @TypeConverter fun toAudioFormat(s: String): AudioFormat = AudioFormat.valueOf(s)
    @TypeConverter fun fromSongSource(s: SongSource): String = s.name
    @TypeConverter fun toSongSource(s: String): SongSource = SongSource.valueOf(s)
}

@Dao interface AccountDao {
    @Query("SELECT * FROM accounts ORDER BY name ASC") fun getAll(): Flow<List<WebDavAccount>>
    @Query("SELECT * FROM accounts WHERE id = :id") suspend fun getById(id: Long): WebDavAccount?
    @Insert(onConflict = OnConflictStrategy.REPLACE) suspend fun insert(a: WebDavAccount): Long
    @Update suspend fun update(a: WebDavAccount)
    @Delete suspend fun delete(a: WebDavAccount)
    @Query("UPDATE accounts SET lastScanned = :t WHERE id = :id") suspend fun updateScanned(id: Long, t: Long)
}

@Dao interface SongDao {
    @Query("SELECT * FROM songs ORDER BY artist,album,trackNumber") fun getAll(): Flow<List<Song>>
    @Query("SELECT * FROM songs WHERE accountId=:id ORDER BY artist,album,trackNumber") fun byAccount(id: Long): Flow<List<Song>>
    @Query("SELECT * FROM songs WHERE source='LOCAL' ORDER BY artist,album,trackNumber") fun getLocal(): Flow<List<Song>>
    @Query("SELECT * FROM songs WHERE album=:a ORDER BY trackNumber,title") fun byAlbum(a: String): Flow<List<Song>>
    @Query("SELECT * FROM songs WHERE artist=:a ORDER BY album,trackNumber") fun byArtist(a: String): Flow<List<Song>>
    @Query("SELECT * FROM songs WHERE isFavorite=1 ORDER BY title") fun getFavorites(): Flow<List<Song>>
    @Query("SELECT DISTINCT artist FROM songs ORDER BY artist") fun getArtists(): Flow<List<String>>
    @Query("SELECT DISTINCT album FROM songs ORDER BY album") fun getAlbums(): Flow<List<String>>
    @Query("SELECT * FROM songs WHERE title LIKE '%'||:q||'%' OR artist LIKE '%'||:q||'%' OR album LIKE '%'||:q||'%' ORDER BY title LIMIT 200")
    fun search(q: String): Flow<List<Song>>
    @Query("SELECT * FROM songs WHERE id=:id") suspend fun getById(id: String): Song?
    @Insert(onConflict = OnConflictStrategy.REPLACE) suspend fun insertAll(songs: List<Song>)
    @Query("UPDATE songs SET isFavorite=:fav WHERE id=:id") suspend fun setFav(id: String, fav: Boolean)
    @Query("DELETE FROM songs WHERE accountId=:id") suspend fun deleteByAccount(id: Long)
    @Query("DELETE FROM songs WHERE source='LOCAL'") suspend fun deleteLocal()
    @Query("SELECT COUNT(*) FROM songs") fun count(): Flow<Int>
}

@Dao interface PlaylistDao {
    @Query("SELECT * FROM playlists ORDER BY isAutoGenerated ASC, name ASC") fun getAll(): Flow<List<Playlist>>
    @Insert(onConflict = OnConflictStrategy.REPLACE) suspend fun insert(p: Playlist): Long
    @Delete suspend fun delete(p: Playlist)
    @Query("DELETE FROM playlists WHERE accountId=:id AND isAutoGenerated=1") suspend fun deleteAutoFor(id: Long)
    @Insert(onConflict = OnConflictStrategy.REPLACE) suspend fun insertSong(ps: PlaylistSong)
    @Query("DELETE FROM playlist_songs WHERE playlistId=:pid") suspend fun clear(pid: Long)
    @Query("DELETE FROM playlist_songs WHERE songId=:sid") suspend fun removeSong(sid: String)
    @Query("SELECT s.* FROM songs s INNER JOIN playlist_songs ps ON s.id=ps.songId WHERE ps.playlistId=:pid ORDER BY ps.position")
    fun getSongs(pid: Long): Flow<List<Song>>
    @Query("UPDATE playlists SET name=:n WHERE id=:id") suspend fun rename(id: Long, n: String)
    @Query("SELECT COUNT(*) FROM playlist_songs WHERE playlistId=:pid") suspend fun songCount(pid: Long): Int
}

@TypeConverters(Converters::class)
@Database(entities=[WebDavAccount::class,Song::class,Playlist::class,PlaylistSong::class], version=3, exportSchema=false)
abstract class AppDatabase : RoomDatabase() {
    abstract fun accountDao(): AccountDao
    abstract fun songDao(): SongDao
    abstract fun playlistDao(): PlaylistDao
    companion object { const val NAME = "webdav_music.db" }
}
