package com.webdavmusic.ui.playlist

import android.os.Bundle
import android.view.*
import android.view.inputmethod.EditorInfo
import androidx.core.view.isVisible
import androidx.fragment.app.activityViewModels
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import com.webdavmusic.data.model.Playlist
import com.webdavmusic.databinding.DialogPlaylistManageBinding
import com.webdavmusic.ui.MainViewModel
import dagger.hilt.android.AndroidEntryPoint

/**
 * Bottom-sheet style dialog for managing a single playlist.
 * Actions: play, rename, clear songs, delete.
 * Auto-generated playlists cannot be renamed or deleted.
 */
@AndroidEntryPoint
class PlaylistManageDialogFragment : androidx.fragment.app.DialogFragment() {

    private var _b: DialogPlaylistManageBinding? = null
    private val b get() = _b!!
    private val vm: MainViewModel by activityViewModels()

    private val playlist by lazy {
        arguments?.let {
            Playlist(
                id             = it.getLong(ARG_ID),
                name           = it.getString(ARG_NAME, ""),
                accountId      = it.getLong(ARG_ACCOUNT, -1L).let { v -> if (v < 0) null else v },
                createdAt      = it.getLong(ARG_CREATED, 0L),
                isAutoGenerated = it.getBoolean(ARG_AUTO, false)
            )
        }
    }

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?) =
        DialogPlaylistManageBinding.inflate(i, c, false).also { _b = it }.root

    override fun onStart() {
        super.onStart()
        dialog?.window?.setLayout(
            (resources.displayMetrics.widthPixels * 0.88).toInt(),
            ViewGroup.LayoutParams.WRAP_CONTENT
        )
    }

    override fun onViewCreated(view: View, s: Bundle?) {
        super.onViewCreated(view, s)
        val pl = playlist ?: return dismiss()
        b.tvTitle.text = "「${pl.name}」"

        // Auto-generated lists can only be played or cleared — no rename/delete
        if (pl.isAutoGenerated) {
            b.btnRename.isVisible = false
            b.btnDelete.isVisible = false
        }

        b.btnPlay.setOnClickListener { vm.playPlaylist(pl.id); dismiss() }
        b.btnClear.setOnClickListener { confirmClear(pl) }
        b.btnDelete.setOnClickListener { confirmDelete(pl) }
        b.btnRename.setOnClickListener { showRenameField(pl) }
        b.btnCancel.setOnClickListener { showButtons() }
        b.btnConfirm.setOnClickListener { submitRename(pl) }

        b.etPlaylistName.setOnEditorActionListener { _, action, _ ->
            if (action == EditorInfo.IME_ACTION_DONE) { submitRename(pl); true } else false
        }
    }

    private fun showRenameField(pl: Playlist) {
        b.buttonsContainer.isVisible = false
        b.inputLayout.isVisible = true
        b.confirmButtons.isVisible = true
        b.etPlaylistName.setText(pl.name)
        b.etPlaylistName.selectAll()
        b.etPlaylistName.requestFocus()
    }

    private fun showButtons() {
        b.buttonsContainer.isVisible = true
        b.inputLayout.isVisible = false
        b.confirmButtons.isVisible = false
    }

    private fun submitRename(pl: Playlist) {
        val name = b.etPlaylistName.text?.toString()?.trim() ?: ""
        if (name.isEmpty()) { b.etPlaylistName.error = "请输入名称"; return }
        vm.renamePlaylist(pl.id, name)
        dismiss()
    }

    private fun confirmClear(pl: Playlist) {
        MaterialAlertDialogBuilder(requireContext())
            .setTitle("清空播放列表")
            .setMessage("确定清空「${pl.name}」中的所有歌曲吗？")
            .setPositiveButton("清空") { _, _ -> vm.clearPlaylist(pl.id); dismiss() }
            .setNegativeButton("取消", null).show()
    }

    private fun confirmDelete(pl: Playlist) {
        MaterialAlertDialogBuilder(requireContext())
            .setTitle("删除播放列表")
            .setMessage("确定删除「${pl.name}」？此操作不可撤销。")
            .setPositiveButton("删除") { _, _ -> vm.deletePlaylist(pl); dismiss() }
            .setNegativeButton("取消", null).show()
    }

    override fun onDestroyView() { super.onDestroyView(); _b = null }

    companion object {
        private const val ARG_ID      = "id"
        private const val ARG_NAME    = "name"
        private const val ARG_ACCOUNT = "account"
        private const val ARG_CREATED = "created"
        private const val ARG_AUTO    = "auto"

        fun of(pl: Playlist) = PlaylistManageDialogFragment().apply {
            arguments = Bundle().apply {
                putLong(ARG_ID, pl.id)
                putString(ARG_NAME, pl.name)
                putLong(ARG_ACCOUNT, pl.accountId ?: -1L)
                putLong(ARG_CREATED, pl.createdAt)
                putBoolean(ARG_AUTO, pl.isAutoGenerated)
            }
        }
    }
}
