package com.webdavmusic.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

enum class SongSource { WEBDAV, LOCAL }

@Entity(tableName = "accounts")
data class WebDavAccount(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val url: String,
    val username: String = "",
    val password: String = "",
    val isActive: Boolean = true,
    val lastScanned: Long = 0L
)

@Entity(tableName = "songs")
data class Song(
    @PrimaryKey val id: String,
    val accountId: Long = -1L,
    val source: SongSource = SongSource.WEBDAV,
    val path: String,
    val url: String,
    val title: String,
    val artist: String = "未知艺术家",
    val album: String = "未知专辑",
    val albumArtist: String = "",
    val trackNumber: Int = 0,
    val duration: Long = 0L,
    val fileSize: Long = 0L,
    val mimeType: String = "",
    val format: AudioFormat = AudioFormat.MP3,
    val dateAdded: Long = System.currentTimeMillis(),
    val lastModified: Long = 0L,
    val artworkPath: String = "",
    val isFavorite: Boolean = false
)

@Entity(tableName = "playlists")
data class Playlist(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val accountId: Long? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val isAutoGenerated: Boolean = false
)

@Entity(tableName = "playlist_songs", primaryKeys = ["playlistId", "songId"])
data class PlaylistSong(val playlistId: Long, val songId: String, val position: Int)

enum class AudioFormat(val extension: String, val mimeType: String) {
    MP3("mp3", "audio/mpeg"),
    FLAC("flac", "audio/flac"),
    WAV("wav", "audio/wav"),
    AAC("aac", "audio/aac"),
    M4A("m4a", "audio/mp4"),
    OPUS("opus", "audio/ogg");

    companion object {
        private val byExt = values().associateBy { it.extension }
        fun fromExtension(ext: String) = byExt[ext.lowercase()]
        val allExtensions = values().map { it.extension }
        fun isAudioFile(name: String) = name.substringAfterLast('.', "").lowercase() in allExtensions
    }
}

data class ScanProgress(
    val accountName: String = "",
    val currentPath: String = "",
    val found: Int = 0,
    val isRunning: Boolean = false,
    val error: String? = null
)

// Lyrics models
data class LyricLine(
    val timeMs: Long,
    val text: String,
    val translated: String = ""
) : Comparable<LyricLine> {
    override fun compareTo(other: LyricLine) = timeMs.compareTo(other.timeMs)
}

enum class LyricType { LRC, ENHANCED_LRC }

data class Lyrics(
    val songId: String,
    val type: LyricType = LyricType.LRC,
    val lines: List<LyricLine> = emptyList(),
    val hasTranslation: Boolean = false,
    val offset: Long = 0L
) {
    val isEmpty get() = lines.isEmpty()

    fun findCurrentIndex(posMs: Long): Int {
        if (lines.isEmpty()) return -1
        val t = posMs + offset
        return lines.indexOfLast { it.timeMs <= t }.coerceAtLeast(0)
    }
}

// Folder browsing
data class BrowseItem(
    val path: String,
    val name: String,
    val isDirectory: Boolean,
    val itemCount: Int = 0       // 0 = unknown
)

data class ScanFolder(
    val path: String,
    val displayName: String,
    val isEnabled: Boolean = true,
    val accountId: Long = -1L
)
