package com.webdavmusic.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

// ─── WebDAV Account ────────────────────────────────────────────────────────────

@Entity(tableName = "accounts")
@Serializable
data class WebDavAccount(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,           // Display name, e.g. "Home NAS"
    val url: String,            // e.g. https://nas.local/dav/music
    val username: String,
    val password: String,
    val isActive: Boolean = true,
    val lastScanned: Long = 0L
)

// ─── Song ──────────────────────────────────────────────────────────────────────

@Entity(tableName = "songs")
@Serializable
data class Song(
    @PrimaryKey
    val id: String,             // Unique: accountId + path hash
    val accountId: Long,
    val path: String,           // Full WebDAV path
    val url: String,            // Direct streaming URL
    val title: String,
    val artist: String = "Unknown Artist",
    val album: String = "Unknown Album",
    val albumArtist: String = "",
    val trackNumber: Int = 0,
    val duration: Long = 0L,    // milliseconds
    val fileSize: Long = 0L,
    val mimeType: String = "",
    val format: AudioFormat = AudioFormat.MP3,
    val dateAdded: Long = System.currentTimeMillis(),
    val lastModified: Long = 0L,
    val artworkUrl: String = "" // Embedded art fetched separately
)

// ─── Playlist ─────────────────────────────────────────────────────────────────

@Entity(tableName = "playlists")
data class Playlist(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,
    val accountId: Long? = null,  // null = all accounts
    val createdAt: Long = System.currentTimeMillis(),
    val isAutoGenerated: Boolean = false
)

@Entity(tableName = "playlist_songs", primaryKeys = ["playlistId", "songId"])
data class PlaylistSong(
    val playlistId: Long,
    val songId: String,
    val position: Int
)

// ─── Audio Formats ─────────────────────────────────────────────────────────────

enum class AudioFormat(val extension: String, val mimeType: String) {
    MP3("mp3", "audio/mpeg"),
    FLAC("flac", "audio/flac"),
    WAV("wav", "audio/wav"),
    AAC("aac", "audio/aac"),
    M4A("m4a", "audio/mp4"),
    OPUS("opus", "audio/ogg");

    companion object {
        private val byExtension = values().associateBy { it.extension }
        private val byMime = values().associateBy { it.mimeType }

        fun fromExtension(ext: String): AudioFormat? = byExtension[ext.lowercase()]
        fun fromMimeType(mime: String): AudioFormat? = byMime[mime.lowercase()]

        val allExtensions = values().map { it.extension }
        val allMimeTypes = values().map { it.mimeType }
    }
}

// ─── Scan Progress ─────────────────────────────────────────────────────────────

data class ScanProgress(
    val accountName: String,
    val currentPath: String,
    val found: Int,
    val total: Int,
    val isRunning: Boolean,
    val error: String? = null
)

// ─── WebDAV File Entry ─────────────────────────────────────────────────────────

data class WebDavFile(
    val path: String,
    val name: String,
    val isDirectory: Boolean,
    val size: Long = 0L,
    val lastModified: Long = 0L,
    val mimeType: String = "",
    val contentType: String = ""
)
